[pytest]
# 避免这种平台差异（Windows 和 Linux 行为可能不同）;不用依赖python -m：将当前路径强制加入环境
pythonpath = .
testpaths = testcases
markers =
    smoke : 冒烟测试（核心功能快速测试）
    regression : 回归测试（全量验证）
    network : 网络相关测试
    auth : 认证相关测试
    business : 业务流程测试
    security : 安全相关测试
    slow : 慢测试（执行时间>1s）
    fast : 块测试
    positive : 正向测试
    negative : 异常测试